version: "3.3"
services:
  s3:
      restart: always
      image: minio/minio:RELEASE.2023-11-01T01-57-10Z-cpuv1
      container_name: S3_minio
      volumes:
        - ./minio_data:/data
      ports:
        - "${MINIO_PORT}:9000"
      networks:
        - frontend
        - backend
      environment:
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_ACCESS_KEY}
      command: server /data
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    
  create_buckets:
    image: minio/mc
    container_name: S3_create_buckets
    depends_on:
      - s3
    networks:
      - backend
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://s3:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_ACCESS_KEY} --api S3v4;
      [[ ! -z "`/usr/bin/mc ls s3 | grep challenge`" ]] || /usr/bin/mc mb s3/${S3_BUCKET_NAME};
      /usr/bin/mc policy download s3/${S3_BUCKET_NAME};
      [[ ! -z "`/usr/bin/mc ls s3 | grep challenge`" ]] || /usr/bin/mc mb s3/${DATA_REPO_BUCKET_NAME};
      /usr/bin/mc policy download s3/${DATA_REPO_BUCKET_NAME};
      exit 0;
      '
      
  triton_server:
    image: nvcr.io/nvidia/tritonserver:23.12-py3
    container_name: triton_server
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - /home/auser/model_repository:/models
    command: ["tritonserver", "--model-repository=/models"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  
volumes:
  minio_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge